name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    container:
      image: php:8.4  # This forces the job to run in a Docker container

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install System Dependencies (Git, Zip, Unzip, GPG)
      run: |
        apt-get update
        apt-get install -y unzip git zip gpg

    - name: Install and Enable extensions
      run: |
        docker-php-ext-install sockets calendar
        docker-php-ext-enable sockets calendar
        pecl install xdebug
        docker-php-ext-enable xdebug

    - name: Install Composer
      run: |
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
        composer --version

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHPUnit with Coverage
      env:
        XDEBUG_MODE: coverage
      run: vendor/bin/phpunit tests --coverage-clover coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: application
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
